### ISSUE TITLE
The json_name field option should be respected for JSON schemas

### ISSUE THREAD

**Issue by ungive** [pubg/protoc-gen-jsonschema#5]
A field like this:

```
float foo_bar_baz = 1 [
    json_name = "fooBarBaz",
    (pubg.jsonschema.field) = {numeric : {exclusive_minimum : 0}}
];
```

Generates output like this:

```
".Message.foo_bar_baz": {
      "type": "number",
      "exclusiveMinimum": 0
}
```

Encoding a simple Message instance where `foo_bar_baz = -1` in Python yields JSON that would be considered valid by the generated JSON schema. JSON generated by the Protobuf library:

```json
{"fooBarBaz": -1.0}
```

Minimal reproducible example: https://github.com/ungive/pub-gprotoc-gen-jsonschema-issue

**Comment by uanid** [comment]
Hi @ungive,

Thank you for creating this issue and letting me know.

I hadn’t understood why this was an issue because, as you can see in the screenshot below, the feature to respect json_name was already working in my local environment. Haha.

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/f0740b78-0b9e-49ac-91bd-c97bce901173">

I also believe that seeing json_name is important. However, the reason I couldn’t add it initially was that I thought some users of this plugin might want to respect json_name, while others might prefer to only use the protobuf field names. So, I thought it should be made as a plugin option to either respect or ignore json_name!

It may take a little time before the official release. For now, I’ll upload a beta [version](https://github.com/pubg/protoc-gen-jsonschema/releases/tag/v0.6.0-jsonname%2B1). would you like to give it a try?

**Comment by ungive** [comment]
Hey @uanid 

I actually went straight ahead and implemented it, including a flag to toggle the behaviour! Adapted the code in the same way you did, adapted the tests, wrote a `proto-json-name` test case and updated the docs.

Only thing not working is the flag itself, it seems that the plugin options variable is always nil. I have no idea why, maybe you know more.
